### ISSUE TITLE
No matching buffer for xxx

### ISSUE THREAD

**Issue by fgheng** [declancm/windex.nvim#1]
Hello, this is a great plugin, I like the maxsize feature, it is so cool, would you like to seperate it as a plugin?

------ split -------
Something goes wrong while I edit the same file in two windows using  command maxzise,

```
E5108: Error executing lua ...site/pack/packer/opt/windex.nvim/lua/windex/maximize.lua:108: Vim(buffer):E94: No matching buffer for ./init.lua
stack traceback:
        [C]: in function 'cmd'
        ...site/pack/packer/opt/windex.nvim/lua/windex/maximize.lua:108: in function 'restore'
        ...site/pack/packer/opt/windex.nvim/lua/windex/maximize.lua:26: in function 'toggle'
        ...vim/site/pack/packer/opt/windex.nvim/lua/windex/init.lua:201: in function 'toggle_nvim_maximize'
        [string ":lua"]:1: in main chunk

```

**Comment by declancm** [comment]
Thank you!! I will definitely do that hopefully within a day or two :)

I'm not sure what the issue is as I have tried doing the same thing with no errors. Would you be able to share your nvim config  or could try maximizing with your other plugins disabled?

**Comment by fgheng** [comment]
hello, recently, I need to take some time to deal with some things. I'll test this problem when I have time

**Comment by declancm** [comment]
No problem! I have separated the maximizing part into its own plugin :)

https://github.com/declancm/maximize.nvim

**Comment by declancm** [comment]
Hi!
Hopefully recent commits have solved this issue. Would you be able to check if you're still having this issue after updating the plugin?
